# **SETUP**

**Load Dataset**

In [259]:
import pandas as pd
pd.set_option('display.max_columns', None)
path = r"C:\Users\KUNAL\Downloads\AI ENGINEER\ProjectsX\global-superstore-analysis\data\superstore_data.csv"

In [260]:
df = pd.read_csv(path)

In [261]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.3312,3,West,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,37033,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,31468,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.2608,2,West,31469,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.1104,1,West,32440,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [262]:
df.tail()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
151285,Furniture,New York City,Uzbekistan,JE-157454,Tracy Hopkins,0.00,LATAM,1,2024-04-12,SS-2024-151286,Low,TEC-MA-10004486,Apple iPhone 5C,75.82,2,Southeast Asia,151286,186,Corporate,2024-04-16,First Class,7.76,Saskatchewan,Bookcases,2024,EU,7
151286,Furniture,Villingen-Schwenningen,United Kingdom,JL-58351,Sam Zeldin,0.00,EU,1,2024-12-11,SS-2024-151287,High,FUR-BO-10004824,Cisco SPA301,0.00,1,Southeast Asia,151287,19,Home Office,2024-12-15,First Class,0.47,Tlemcen,Supplies,2024,APAC,26
151287,Office Supplies,Nottingham,Paraguay,KN-164502,Dennis Kane,0.36,LATAM,1,2024-12-11,SS-2024-151288,Low,OFF-BIC-10001823,"Jiffy Manila Envelope, Recycled",0.00,1,West,151288,39,Home Office,2024-12-16,Second Class,3.84,Valparaíso,Phones,2024,Africa,11
151288,Technology,Broken Arrow,Iran,DA-134504,Brendan Dodson,0.00,Africa,1,2024-01-23,SS-2024-151289,High,OFF-KRA-10000117,Logitech Wireless Headset h800,1.76,3,Oceania,151289,88,Corporate,2024-01-27,Second Class,81.03,Vermont,Bookcases,2024,EMEA,27
151289,Technology,Madison,Guadeloupe,DW-35851,Brooke Gillingham,0.00,EU,1,2024-11-28,SS-2024-151290,Low,OFF-AP-10003266,"Brother Fax and Copier, High-Speed",0.00,1,Central,151290,84,Consumer,2024-12-05,Standard Class,64.23,Sofiya-Grad,Labels,2024,EU,38

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151290 entries, 0 to 151289
Data columns (total 27 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Category        151290 non-null  object
 1   City            151290 non-null  object
 2   Country         151290 non-null  object
 3   Customer.ID     151290 non-null  object
 4   Customer.Name   151290 non-null  object
 5   Discount        151290 non-null  float64
 6   Market          151290 non-null  object
 7   记录数             151290 non-null  int64
 8   Order.Date      151290 non-null  object
 9   Order.ID        151290 non-null  object
 10  Order.Priority  151290 non-null  object
 11  Product.ID      151290 non-null  object
 12  Product.Name    151290 non-null  object
 13  Profit          151290 non-null  float64
 14  Quantity        151290 non-null  int64
 15  Region          151290 non-null  object
 16  Row.ID          151290 non-null  int64
 17  Sales           151290 non-null  int64
 18  Segment         151290 non-null  object
 19  Ship.Date       151290 non-null  object
 20  Ship.Mode       151290 non-null  object
 21  Shipping.Cost   151290 non-null  float64
 22  State           151290 non-null  object
 23  Sub.Category    151290 non-null  object
 24  Year            151290 non-null  int64
 25  Market2         151290 non-null  object
 26  weeknum         151290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 31.2+ MB

In [264]:
df.describe()

,Discount,记录数,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,151290.000000,151290.0,151290.000000,151290.000000,151290.00000,151290.000000,151290.000000,151290.000000,151290.000000
mean,0.143671,1.0,40.713125,3.476218,75645.50000,246.220523,26.459589,2017.220854,31.272549
std,0.228715,0.0,169.171275,2.485409,43673.80545,514.249724,62.038206,3.998792,14.420462
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.000000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,37823.25000,28.000000,2.350000,2014.000000,20.000000
50%,0.000000,1.0,8.500000,3.000000,75645.50000,80.000000,7.280000,2017.000000,33.000000
75%,0.200000,1.0,35.190000,5.000000,113467.75000,245.000000,23.270000,2021.000000,44.000000
max,2.010000,1.0,13639.130000,25.000000,151290.00000,28837.000000,1636.970000,2024.000000,53.000000

**Identify Data Issues**

In [265]:
df.isna().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
记录数               0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [266]:
df.duplicated().sum()

np.int64(0)

In [267]:
df.dtypes

Category           object
City               object
Country            object
Customer.ID        object
Customer.Name      object
Discount          float64
Market             object
记录数                 int64
Order.Date         object
Order.ID           object
Order.Priority     object
Product.ID         object
Product.Name       object
Profit            float64
Quantity            int64
Region             object
Row.ID              int64
Sales               int64
Segment            object
Ship.Date          object
Ship.Mode          object
Shipping.Cost     float64
State              object
Sub.Category       object
Year                int64
Market2            object
weeknum             int64
dtype: object

# **DATA CLEANING PIPELINE**

In [268]:
df.head(1)

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.3312,3,West,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2

**Change Columns Name**

In [269]:
df.columns = [
    "category", "city", "country", "customer_id", "customer_name",
    "discount", "market", "record_count", "order_date", "order_id",
    "order_priority", "product_id", "product_name", "profit", "quantity",
    "region", "row_id", "sales", "segment", "ship_date", "ship_mode",
    "shipping_cost", "state", "sub_category", "year", "market2", "weeknum"
]

In [270]:
df.head(1)

,category,city,country,customer_id,customer_name,discount,market,record_count,order_date,order_id,order_priority,product_id,product_name,profit,quantity,region,row_id,sales,segment,ship_date,ship_mode,shipping_cost,state,sub_category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.3312,3,West,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2

In [271]:
df.dtypes

category           object
city               object
country            object
customer_id        object
customer_name      object
discount          float64
market             object
record_count        int64
order_date         object
order_id           object
order_priority     object
product_id         object
product_name       object
profit            float64
quantity            int64
region             object
row_id              int64
sales               int64
segment            object
ship_date          object
ship_mode          object
shipping_cost     float64
state              object
sub_category       object
year                int64
market2            object
weeknum             int64
dtype: object

**Convert Dates**

In [272]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed')
df['ship_date'] = pd.to_datetime(df['ship_date'], format='mixed')

In [273]:
df["order_date"].dtype

dtype('<M8[ns]')

**Remove Duplicates**

In [274]:
df = df.drop_duplicates()

**Clean Numeric Columns**

In [275]:
num_cols = ['discount', 'record_count', 'profit', 'quantity', 'row_id', 'sales','shipping_cost', 'year', 'weeknum']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors="coerce")

**Handle Missing Values**

In [276]:
df.head()

,category,city,country,customer_id,customer_name,discount,market,record_count,order_date,order_id,order_priority,product_id,product_name,profit,quantity,region,row_id,sales,segment,ship_date,ship_mode,shipping_cost,state,sub_category,year,market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.3312,3,West,36624,19,Consumer,2011-01-09,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.2928,2,West,37033,19,Consumer,2011-01-26,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.8418,3,West,31468,21,Consumer,2011-08-09,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.2608,2,West,31469,111,Consumer,2011-08-09,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.1104,1,West,32440,6,Consumer,2011-10-03,Standard Class,1.32,California,Paper,2011,North America,40

In [277]:
df = df.dropna(subset=['order_id','customer_id','product_id','order_date','sales','profit','quantity'])
df["discount"] = df['discount'].fillna(df["discount"].mean())
df["shipping_cost"] = df["shipping_cost"].fillna(df['shipping_cost'].median())
df["segment"] = df['segment'].fillna(df['segment'].fillna("Unknown"))

**Save Cleaned Data**

In [278]:
df.to_csv(r"C:\Users\KUNAL\Downloads\AI ENGINEER\ProjectsX\global-superstore-analysis\data\superstore_cleaned.csv",index=False)